/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_com_plustv_SmartCard */

#ifndef _Included_cn_com_plustv_SmartCard
#define _Included_cn_com_plustv_SmartCard
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_com_plustv_SmartCard
 * Method:    M2CLogoCgKeyerUpLoadFile
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_cn_com_plustv_SmartCard_M2CLogoCgKeyerUpLoadFile
  (JNIEnv *, jobject, jstring);

/*
 * Class:     cn_com_plustv_SmartCard
 * Method:    M2CLogoCgKeyerDeleteFile
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_cn_com_plustv_SmartCard_M2CLogoCgKeyerDeleteFile
  (JNIEnv *, jobject, jstring);

/*
 * Class:     cn_com_plustv_SmartCard
 * Method:    M2CLogoCgKeyerSetupLogo
 * Signature: (Ljava/lang/String;IIZ)Z
 */
JNIEXPORT jboolean JNICALL Java_cn_com_plustv_SmartCard_M2CLogoCgKeyerSetupLogo
  (JNIEnv *, jobject, jstring, jint, jint, jboolean);

/*
 * Class:     cn_com_plustv_SmartCard
 * Method:    M2CLogoCgKeyerCancelLogo
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_cn_com_plustv_SmartCard_M2CLogoCgKeyerCancelLogo
  (JNIEnv *, jobject, jstring);

/*
 * Class:     cn_com_plustv_SmartCard
 * Method:    M2CLogoCgKeyerGetSystemCapacity
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_cn_com_plustv_SmartCard_M2CLogoCgKeyerGetSystemCapacity
  (JNIEnv *, jobject, jint);

/*
 * Class:     cn_com_plustv_SmartCard
 * Method:    M2CLogoCgKeyerLogoFileList
 * Signature: (Ljava/lang/String;I)Z
 */
JNIEXPORT jboolean JNICALL Java_cn_com_plustv_SmartCard_M2CLogoCgKeyerLogoFileList
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     cn_com_plustv_SmartCard
 * Method:    M2CLogoCgKeyerGetErrorString
 * Signature: (ILjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_cn_com_plustv_SmartCard_M2CLogoCgKeyerGetErrorString
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     cn_com_plustv_SmartCard
 * Method:    M2CLogoCgKeyerDeletePayout
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_cn_com_plustv_SmartCard_M2CLogoCgKeyerDeletePayout
  (JNIEnv *, jobject);

/*
 * Class:     cn_com_plustv_SmartCard
 * Method:    M2CLogoCgKeyerGetPayout
 * Signature: (Ljava/lang/String;I)Z
 */
JNIEXPORT jboolean JNICALL Java_cn_com_plustv_SmartCard_M2CLogoCgKeyerGetPayout
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     cn_com_plustv_SmartCard
 * Method:    M2CLogoCgKeyerGetFileInfo
 * Signature: (Ljava/lang/String;Lcn/com/plustv/M2cLogoInfo_t;)Z
 */
JNIEXPORT jboolean JNICALL Java_cn_com_plustv_SmartCard_M2CLogoCgKeyerGetFileInfo
  (JNIEnv *, jobject, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
